backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "specials"
    label: "Daily Specials"
    folder: "content/specials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Special Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Details", name: "body", widget: "markdown"}
